version: '3.3'

services:

  localstack:
    image: localstack/localstack:2.0.2
    ports:
      - "4566:4566"
      - "4510-4559:4510-4559"
    environment:
      - SERVICES=kinesis,dynamodb
      - DEFAULT_REGION=ap-southeast-1
      - USE_SINGLE_REGION=true
    volumes:
      - localstack:/tmp/localstack
      - ./localstack/ready.sh:/etc/localstack/init/ready.d/start.sh

volumes:
  localstack:
